package com.example.myproperties.domain.model.rules

enum class PropertyInfoValidationModel{
    EMPTY_PROPERTY_TYPE,
    EMPTY_PROPERTY_TYPE_NAME,
    EMPTY_DESCRIPTION,
    EMPTY_TITLE,
    EMPTY_MAX_GUESTS_NUMBER,
    EMPTY_BEDS_NUMBER,
    EMPTY_BATHROOMS_NUMBER,
    EMPTY_LOCATION,
    EMPTY_OR_NOT_ENOUGH_PHOTOS_LIST,
    SUCCESS_VALIDATION
}